(defpackage #:paiprolog
  (:use #:cl )
  (:shadow #:ignore #:symbol #:debug)
  (:export #:?-
           #:<-
           #:<--
           #:?
           #:fail
           #:true
           #:call
           #:!
           #:and
           #:or
           #:if
           #:catch
           #:throw
           #:=
           #:unify-with-occurs-check
           #:\\=
           #:var
           #:atom
           #:integer
           #:real
           #:atomic
           #:compound
           #:nonvar
           #:number
           #:==
           #:\\==
           #:@<
           #:@=<
           #:@>2
           #:@>=
           #:functor
           #:arg
           #:copy-term
           #:is
           #:|=:=|
           #:=\\=
           #:<
           #:=<
           #:>
           #:>=
           #:clause
           #:current-predicate
           #:asserta
           #:assertz
           #:retract
           #:abolish
           #:findall
           #:bagof
           #:current-input
           #:current-output
           #:set-input
           #:set-output
           #:close
           #:flush-output
           #:stream-property
           #:at-end-of-stream
           #:set-stream-position
           #:get-char
           #:put-char
           #:nl
           #:get-code
           #:put-code
           #:read
           #:write
           #:fail-if
           #:once
           #:repeat
           #:atom-length
           #:atom-concat
           #:sub-atom
           #:atom-chars
           #:atom-codes
           #:char-code
           #:number-chars
           #:number-codes
           #:lisp
           #:prolog
           #:prolog-collect
           #:prolog-first))
